/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quasivirtuallock.concept;

import com.quasivirtuallock.threads.ExportThread;
import java.awt.Rectangle;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Mar Omay
 */
public class FileMenu extends javax.swing.JFrame {

    /**
     * Creates new form FileMenu
     */
    
    private static String[] s;
    private static DashboardAdd dashboard;
    
    public boolean hoverable = true;
    
    public FileMenu(String[] s, DashboardAdd dashboard) {
        initComponents();
        filenameLabel.setText(s[0]);
        sizeLabel.setText(s[1]);
        dateLabel.setText(s[2]);
        this.s = s;
        this.dashboard = dashboard;
        dashboard.setEnabled(false);
        
        exportingLabel.setVisible(false);
        percentLabel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filenameLabel = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        exportLabel = new javax.swing.JLabel();
        deleteLabel = new javax.swing.JLabel();
        exportingLabel = new javax.swing.JLabel();
        percentLabel = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        filenameLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 17)); // NOI18N
        filenameLabel.setForeground(new java.awt.Color(255, 255, 255));
        filenameLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        filenameLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(filenameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 125, 270, 22));

        sizeLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 17)); // NOI18N
        sizeLabel.setForeground(new java.awt.Color(255, 255, 255));
        sizeLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        sizeLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(sizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 180, 270, 22));

        dateLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 17)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        dateLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 234, 270, 22));

        closeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        getContentPane().add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 11, 25, 25));

        exportLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exportLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exportLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exportLabelMouseExited(evt);
            }
        });
        getContentPane().add(exportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 85, 100, 39));

        deleteLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteLabelMouseExited(evt);
            }
        });
        getContentPane().add(deleteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 143, 100, 39));

        exportingLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        exportingLabel.setForeground(new java.awt.Color(255, 255, 255));
        exportingLabel.setText("Exporting...");
        getContentPane().add(exportingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 90, 30));

        percentLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        percentLabel.setForeground(new java.awt.Color(255, 255, 255));
        percentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        percentLabel.setText("100%");
        getContentPane().add(percentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 100, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quasivirtuallock/concept/filemenu.png"))); // NOI18N
        bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        if (hoverable){
            this.dispose();
            dashboard.setEnabled(true);
            dashboard.requestFocus();
        }
    }//GEN-LAST:event_closeLabelMouseClicked

    private void exportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportLabelMouseClicked
        if (hoverable){
            JFileChooser fc = new JFileChooser();
            fc.setCurrentDirectory(new File(System.getProperty("user.home")));
            fc.setDialogTitle("Export to");
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int result = fc.showSaveDialog(this);
            if (result == JFileChooser.APPROVE_OPTION){
                new ExportThread(this, s[0], fc.getSelectedFile().getAbsolutePath()).startThread();
            }
        }
    }//GEN-LAST:event_exportLabelMouseClicked

    private void deleteLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLabelMouseClicked
        if (hoverable){
            hoverable = false;
            int result = JOptionPane.showConfirmDialog(this, "Do you want to delete this file?", "QVL", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION){
                LoadingScreen loading = new LoadingScreen();
                loading.setLocation(dashboard.getX() + dashboard.getWidth() / 2 - loading.getWidth() / 2,
                            dashboard.getY() + dashboard.getHeight() / 2 - loading.getHeight() / 2);
                loading.setVisible(true);
                try{
                    result = QVL.STATEMENT.executeUpdate("DELETE FROM files WHERE id = " + QVL.rowToId.get(s[3]));
                    QVL.rowToId.clear();
                    JOptionPane.showMessageDialog(this, "File deleted successfully.", "QVL", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    dashboard.setEnabled(true);
                    dashboard.requestFocus();
                    dashboard.openAdd();
                    dashboard.openVault();
                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Unable to delete file", "QVL", JOptionPane.ERROR_MESSAGE);
                }
                loading.dispose();
                hoverable = true;
            }
        }
    }//GEN-LAST:event_deleteLabelMouseClicked

    private void exportLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportLabelMouseExited
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quasivirtuallock/concept/filemenu.png")));
    }//GEN-LAST:event_exportLabelMouseExited

    private void deleteLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLabelMouseExited
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quasivirtuallock/concept/filemenu.png")));
    }//GEN-LAST:event_deleteLabelMouseExited

    private void exportLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportLabelMouseEntered
        if (hoverable)
            bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quasivirtuallock/concept/filemenu-hover-export.png")));
    }//GEN-LAST:event_exportLabelMouseEntered

    private void deleteLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLabelMouseEntered
        if (hoverable)
            bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quasivirtuallock/concept/filemenu-hover-delete.png")));
    }//GEN-LAST:event_deleteLabelMouseEntered

    private int posX, posY; 
    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        Rectangle rect = getBounds();
        this.setBounds(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY, rect.width, rect.height);
    }//GEN-LAST:event_bgMouseDragged

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileMenu(s, dashboard).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    public javax.swing.JLabel closeLabel;
    private javax.swing.JLabel dateLabel;
    public javax.swing.JLabel deleteLabel;
    public javax.swing.JLabel exportLabel;
    public javax.swing.JLabel exportingLabel;
    private javax.swing.JLabel filenameLabel;
    public javax.swing.JLabel percentLabel;
    private javax.swing.JLabel sizeLabel;
    // End of variables declaration//GEN-END:variables
}
